services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - caronte
    networks:
      - caronte-network
      
  caronte:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_ADDRESS=mongo:27017
    ports:
      - ":3333"
    depends_on:
      - mongo
    networks:
      - caronte-network
    volumes:
      - ./uploads:/app/uploads
      - ./storage:/app/storage
  
  mongo:
    image: mongo:4.2
    volumes:
      - mongo-data:/data/db
    networks:
      - caronte-network

networks:
  caronte-network:

volumes:
  mongo-data:
