FROM nginx:alpine

# Installazione apache2-utils per htpasswd
RUN apk add --no-cache apache2-utils

# Copia della configurazione nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia del file .htpasswd
COPY .htpasswd /etc/nginx/.htpasswd

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]